### ISSUE TITLE
UserMap

### ISSUE THREAD

**Issue by fjbsaper** [tdotrob/IBMMQ-passwd-auth#1]
**User Map** _works_ with adopt the authenticated user. It just works differently:
i.e. your usermap rule needs to have as clntuser the authenticated user. You can then map that user to a different user that is authorized for the app.  (tried in 8.0.0.5 )
**BlockUser**
Looking at the blockuser setup, why the userlist(_nobody) and not just ('nobody') ?
Left '_nobody' for the usermca on the channel (just in case user nobody would exist)

**Case 3**
Color me confused between usersrc(channel) and usersrc(noAccess)... Modelling on reverse T.Rob entries:
  Case 3 usersrc(noaccess)
  Case 4 usersrc(channel)

**Comment by tdotrob** [comment]
> User Map works with adopt the authenticated user. It just works differently:
> i.e. your usermap rule needs to have as clntuser the authenticated user. You can then map that user to 
> a different user that is authorized for the app. (tried in 8.0.0.5 )

I didn't find that to be true at all.  Are you sure that ADOPTCTX had been set before connecting?  And if you are sure that works, what was the test environment?

> Looking at the blockuser setup, why the userlist(nobody) and not just ('nobody') ?
> Left 'nobody' for the usermca on the channel (just in case user nobody would exist)

Mark Taylor convinced me to use a value that cannot be a valid user ID and does not resemble MQ reserved words.  So any place that I need a value that can't exist as a User ID it's *NOBODY.  The Upper case also sets it off from actual user IDs.  I'll change this back before/during/after the merge.  (First time using GitHub so I'm not sure how that works.)

> Color me confused between usersrc(channel) and usersrc(noAccess)... 

When it sets USERSRC(MAP) or USERSRC(CHANNEL) it sets these for both possible CLNTUSER values.  When it sets USERSRC(NOACCESS) it does so for only one of the possible CLNTUSER values at a time.  When one of these blocks the connection, we need to know _which_ one it is.  Only way to do that is try them one at a time.  As you have commented out half the tests, this one won't work.  I'll change those to pick up the signed-in user.

Cases #3 and #4 also make sure the one not set to NOACCESS is using USERSRC(CHANNEL) because USERSRC(MAP) is a less reliable indicator of success.

> This script must be run from an account with elevated administrator

Why?  Many of my clients run MQ on a service account that is _not_ a local Windows admin using personal accounts that are in Domain mqm but not local admins.  My intention was to accommodate their need for MQ Admins to be able to run the tools without getting domain admins or server admins involved.

**Comment by fjbsaper** [comment]
You're right. I missed an important distinction: Although I did have adoptctx(yes) I did not have the setting as required but only as **required admin** and none of the users (clnt user or mapped user) were privileged users...

*NOBODY makes sense as explained. will change my setup.

I get you on wanting to try with 2 users. Will take some time to figure it out because typically you're signed in only with the logged on user (windows) unless your machine is virtual... and I have never seen the NOACCESS policy not to work, unless the clntuser was not what you expected (working as designed).

Agreed for the privileges and I will revert. **Quirk with windows 10 home** as IIB10 adds you to the mqbrokers group, there is no easy way to get added to the mqm group. ( lusrmgr.msc snap-in is not allowed for that version of windows!) I.E. you have to use the elevated command prompt.
Such a shame that mqsisetsecurity does not display any parameters like group and user, but then I suspect that would be in violation of security....
Will let you know when the pull request is ready again.

**Comment by tdotrob** [comment]
>  lusrmgr.msc snap-in
> I type  lusrmgr.msc into the search box and hit enter.  Does that work for me only because I have Win10Pro?  As per the added comments, this absolutely does not work if you can't add users for usermap1, usermap2, peermap1, and addrmap1, and these have to have access.  I suppose we could figure out what group they are in by default and give it +conn, +inq, +dsp access for the duration of the testing.

**Comment by fjbsaper** [comment]
Yup lusrmgr.msc does not work in Windows home edition.
You can add the users in home edition and you only have 2 types: admin and non admin users.
Guess now that would mean that you have to allocation the permissions at the principal level, or that you need a tool like mqsisecurity but with a lot more options to create the groups and assign users to them...

**Comment by tdotrob** [comment]
Or run it in a Linux VM.  I'm posting a tutorial today or tomorrow showing how to spin up an Linux VM with MQ using all free components.  Anyone needing to test a Windows QMgr will either need to get Windows Pro in a VM, or upgrade their workstation.  Can't help that.  But Linux/UNIX users should be well served with the tutorial.
